name: 'Update PR Branch'
description: 'Automatically update the branch of newest ready to merge PR. Designed to work with the auto-merge option.'
branding:
  icon: git-pull-request
  color: orange
inputs:
  token:
    description: 'The GitHub personal access token'
    required: true
  required_approval_count:
    required: true
    description: 'The action will skip PRs that have less approvals than this value'
    default: '2'
runs:
  using: 'node12'
  main: 'dest/index.js'
